# Generated by Django 4.1 on 2022-09-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Профайл',
        ),
    ]
