# Generated by Django 4.1 on 2022-10-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0002_order_delivery_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
