# Generated by Django 4.1 on 2022-10-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0004_order_product_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_method',
            new_name='delivery_method_express',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='payment_method_someone',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method_ordinary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method_online',
            field=models.BooleanField(default=True),
        ),
    ]
