# Generated by Django 4.1 on 2022-10-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0005_rename_delivery_method_order_delivery_method_express_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_method_express',
            new_name='delivery_method',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method_someone',
            new_name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_method_ordinary',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method_online',
        ),
    ]
