# Generated by Django 4.1 on 2022-10-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0006_rename_delivery_method_express_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
    ]
