# Generated by Django 4.1 on 2022-10-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0007_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_order',
            field=models.IntegerField(default=0),
        ),
    ]
