# Generated by Django 4.1 on 2022-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0009_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='text_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
