# Generated by Django 4.1 on 2022-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ordering', '0010_order_code_error_order_status_order_text_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='count_product',
            field=models.IntegerField(default=0),
        ),
    ]
