# Generated by Django 4.1 on 2022-08-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Загрузить изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pieces_left',
            field=models.IntegerField(verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Категории',
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='Отзывы',
        ),
    ]
