# Generated by Django 4.1 on 2022-09-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_alter_category_options_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.IntegerField(default=0, verbose_name='количество продаж'),
        ),
    ]
