# Generated by Django 4.1 on 2022-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_product_number_of_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_category',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Загрузить иконку категории'),
        ),
    ]
