# Generated by Django 4.1 on 2022-09-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0005_category_img_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_category',
        ),
    ]
