# Generated by Django 4.1 on 2022-09-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0009_subcategory_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='Подкатегория',
        ),
    ]
